# Generated by Django 5.2 on 2025-04-08 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.CharField(max_length=100)),
                ('equipment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Laboratório',
                'verbose_name_plural': 'Laboratórios',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='schedulerequest',
            name='materials_needed',
        ),
        migrations.AlterModelOptions(
            name='schedulerequest',
            options={'ordering': ['-scheduled_date', 'start_time'], 'verbose_name': 'Solicitação de Agendamento', 'verbose_name_plural': 'Solicitações de Agendamento'},
        ),
        migrations.RemoveField(
            model_name='schedulerequest',
            name='purpose',
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='description',
            field=models.TextField(default='0', verbose_name='Descrição da atividade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='materials',
            field=models.TextField(blank=True, null=True, verbose_name='Materiais necessários'),
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='number_of_students',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de alunos'),
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='subject',
            field=models.CharField(default='0', max_length=100, verbose_name='Assunto/Disciplina'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='end_time',
            field=models.TimeField(verbose_name='Hora de término'),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='scheduled_date',
            field=models.DateField(verbose_name='Data agendada'),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='start_time',
            field=models.TimeField(verbose_name='Hora de início'),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.laboratory'),
        ),
        migrations.DeleteModel(
            name='RequestedMaterial',
        ),
    ]
