# Generated by Django 5.2 on 2025-04-15 01:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_laboratory_remove_schedulerequest_materials_needed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftScheduleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, verbose_name='Assunto/Disciplina')),
                ('description', models.TextField(verbose_name='Descrição da atividade')),
                ('scheduled_date', models.DateField(verbose_name='Data agendada')),
                ('start_time', models.TimeField(verbose_name='Hora de início')),
                ('end_time', models.TimeField(verbose_name='Hora de término')),
                ('number_of_students', models.IntegerField(blank=True, null=True, verbose_name='Número de alunos')),
                ('materials', models.TextField(blank=True, null=True, verbose_name='Materiais necessários')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.laboratory')),
                ('professor', models.ForeignKey(limit_choices_to={'user_type': 'professor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rascunho de Agendamento',
                'verbose_name_plural': 'Rascunhos de Agendamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
