# Generated by Django 5.2 on 2025-04-15 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0002_alter_laboratory_options_laboratory_created_at_and_more'),
        ('scheduling', '0003_draftschedulerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerequest',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratories.laboratory'),
        ),
        migrations.AlterField(
            model_name='draftschedulerequest',
            name='laboratory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratories.laboratory'),
        ),
        migrations.DeleteModel(
            name='Laboratory',
        ),
    ]
