# Generated by Django 5.2 on 2025-04-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0004_alter_schedulerequest_laboratory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftschedulerequest',
            name='shift',
            field=models.CharField(choices=[('morning', 'Matutino (08:00 - 12:00)'), ('evening', 'Noturno (19:00 - 22:00)')], default='evening', max_length=20),
        ),
    ]
