# Generated by Django 5.2 on 2025-04-15 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0005_draftschedulerequest_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftschedulerequest',
            name='guide_file',
            field=models.FileField(blank=True, null=True, upload_to='lab_guides/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'odt'])], verbose_name='Roteiro de Aula'),
        ),
        migrations.AddField(
            model_name='schedulerequest',
            name='guide_file',
            field=models.FileField(blank=True, null=True, upload_to='lab_guides/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'odt'])], verbose_name='Roteiro de Aula'),
        ),
    ]
