# Generated by Django 5.2 on 2025-04-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0006_draftschedulerequest_guide_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftschedulerequest',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de término'),
        ),
        migrations.AlterField(
            model_name='draftschedulerequest',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de início'),
        ),
    ]
