# Generated by Django 5.2 on 2025-07-31 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_fileattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulerequest',
            name='class_semester',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Semestre/Turma'),
        ),
    ]
