# Generated by Django 5.2 on 2025-08-04 20:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0010_make_department_nullable'),
        ('scheduling', '0011_make_description_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schedulerequest',
            index=models.Index(fields=['status'], name='scheduling_status_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerequest',
            index=models.Index(fields=['status', '-request_date'], name='scheduling_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerequest',
            index=models.Index(fields=['professor', 'status'], name='scheduling_prof_status_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulerequest',
            index=models.Index(fields=['laboratory', 'scheduled_date', 'status'], name='scheduling_lab_date_status_idx'),
        ),
    ]
