# Generated by Django 5.2 on 2025-08-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0012_schedulerequest_scheduling_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerequest',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de término'),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data agendada'),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de início'),
        ),
        migrations.AlterField(
            model_name='schedulerequest',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Assunto/Disciplina'),
        ),
    ]
