# Generated by Django 5.1.7 on 2025-08-11 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0013_make_scheduling_fields_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRequestComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schedule_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='scheduling.schedulerequest')),
            ],
            options={
                'verbose_name': 'Comentário do Agendamento',
                'verbose_name_plural': 'Comentários dos Agendamentos',
                'ordering': ['created_at'],
            },
        ),
    ]
