# Generated by Django 5.2 on 2025-08-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0014_schedulerequestcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado')], default='pending', max_length=15),
        ),
    ]
