# Generated by Django 5.2 on 2025-04-15 16:37

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laboratory',
            options={'ordering': ['name'], 'verbose_name': 'Laboratório', 'verbose_name_plural': 'Laboratórios'},
        ),
        migrations.AddField(
            model_name='laboratory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='department',
            field=models.CharField(default=datetime.datetime(2025, 4, 15, 13, 37, 30, 118458), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='equipment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
