# Generated by Django 5.2 on 2025-07-08 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0008_add_multiple_technicians'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='department',
            field=models.CharField(blank=True, choices=[('exatas', 'Exatas'), ('saude', 'Saúde'), ('informatica', 'Informática')], help_text='Este campo será substituído em breve', max_length=100, null=True, verbose_name='Departamento (Antigo)'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='Capacidade'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='departments',
            field=models.ManyToManyField(blank=True, help_text='Selecione os departamentos aos quais este laboratório pertence', to='laboratories.department', verbose_name='Departamentos'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='equipment',
            field=models.TextField(blank=True, null=True, verbose_name='Equipamentos'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='responsible_technician',
            field=models.ForeignKey(blank=True, help_text='Este campo será substituído em breve', limit_choices_to={'user_type': 'technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável (Antigo)'),
        ),
    ]
