# Generated by Django 5.2 on 2025-08-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratories', '0010_make_department_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='is_storage',
            field=models.BooleanField(default=False, help_text='Marque se este laboratório é usado apenas para armazenar materiais (não disponível para agendamento)', verbose_name='Estoque/Armazenamento'),
        ),
    ]
