"""
Django settings for LabConnect project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from django.contrib.messages import constants as messages
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-s!9v%s#j@@tjx#=82c5id%t=(w4!pxxi331rnb!n_4^21$tty1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Third-party apps
    'crispy_forms',
    'crispy_bootstrap5',
    'rest_framework',

    # Local apps
    'accounts.apps.AccountsConfig',
    'laboratories.apps.LaboratoriesConfig',
    'inventory.apps.InventoryConfig',
    'scheduling.apps.SchedulingConfig',
    'dashboard.apps.DashboardConfig',
    'reports.apps.ReportsConfig',
    'api.apps.ApiConfig',
    'whatsapp',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LabConnect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.sidebar_context',
            ],
        },
    },
]


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Configurações de autenticação para allauth
AUTHENTICATION_BACKENDS = [
    # Backends padrão do Django
    'django.contrib.auth.backends.ModelBackend',
    # Opcional: se quiser usar o Microsoft Auth para login também
    'microsoft_auth.backends.MicrosoftAuthenticationBackend',
]

# Configura para usar apenas email, não login de usuários
MICROSOFT_AUTH = {
    'TENANT_ID': 'common',
    'CLIENT_ID': 'ba2e5c7c-f3d1-4aa7-b3a7-65bcbbab7ed6',
    'CLIENT_SECRET': '83b1545f-9e88-4499-aae0-57ff5786409a',
    'REDIRECT_URI': 'http://localhost:8000/oauth/callback',
    'SCOPE': ['Mail.Send'],
    'LOGIN_ENABLED': False,  # Desabilita login Microsoft, mantém apenas email
}




# Configurações adicionais para allauth
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_UNIQUE_EMAIL = True

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Authentication settings
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard_redirect'
LOGOUT_REDIRECT_URL = 'login'

# Crispy forms
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

# Message tags
MESSAGE_TAGS = {
    messages.DEBUG: 'alert-secondary',
    messages.INFO: 'alert-info',
    messages.SUCCESS: 'alert-success',
    messages.WARNING: 'alert-warning',
    messages.ERROR: 'alert-danger',
}

# Configuração do Sites Framework
SITE_ID = 1

# Email settings
MS_CLIENT_ID = 'ba2e5c7c-f3d1-4aa7-b3a7-65bcbbab7ed6'  # Mesmo do MICROSOFT_AUTH
MS_CLIENT_SECRET = '83b1545f-9e88-4499-aae0-57ff5786409a'  # Mesmo do MICROSOFT_AUTH
MS_TENANT_ID = 'common'  # Usando o mesmo valor de MICROSOFT_AUTH TENANT_ID
MS_SENDER_EMAIL = 'labconnectua@outlook.com'  # Email que enviará as mensagens

EMAIL_BACKEND = 'sendgrid_backend.SendgridBackend'
SENDGRID_API_KEY = os.environ.get('SENDGRID_API_KEY', '')
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER', 'labconnectua@outlook.com')
SENDGRID_SANDBOX_MODE_IN_DEBUG = False  # Define como False quando estiver pronto para enviar emails reais
SENDGRID_ECHO_TO_STDOUT = True  # Para depuração - mostra os emails no console também

# URL base do sistema (usado nos emails)
BASE_URL = 'http://localhost:8000'

# Domínios de email permitidos para registro
ALLOWED_EMAIL_DOMAINS = [
    'cogna.com.br',
    'kroton.com.br',
]


# Configurações para Ollama (Llama local)
OLLAMA_API_URL = 'http://localhost:11434/api/chat'
OLLAMA_MODEL = 'llama3' 

# Configurações do Docling
DOCLING_ENABLED = True
DOCLING_MODEL = "pt_core_news_sm"  # Modelo em português
DOCLING_CACHE_DIR = os.path.join(BASE_DIR, 'docling_cache')

ALLOW_SCHEDULING_ANY_DAY = True

# Configurações WhatsApp
WHATSAPP_ENABLED = True  # Ative ou desative o serviço
WHATSAPP_SERVICE_URL = 'http://localhost:3000/api'  # URL do serviço Node.js