# Generated by Django 5.2 on 2025-04-07 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('material_type', models.CharField(choices=[('consumable', 'Consumível'), ('permanent', 'Permanente'), ('perishable', 'Perecível')], max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Material Categories',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('minimum_stock', models.PositiveIntegerField(help_text='Minimum quantity before alert')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='laboratories.laboratory')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.materialcategory')),
            ],
        ),
    ]
