# Generated by Django 5.2 on 2025-04-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='analyzed_data',
            field=models.JSONField(blank=True, help_text='Dados da análise por NLP', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='suggested_category',
            field=models.CharField(blank=True, help_text='Categoria sugerida pelo sistema', max_length=50),
        ),
    ]
