# Generated by Django 5.2 on 2025-04-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_material_analyzed_data_material_suggested_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
