# Generated by Django 5.2 on 2025-04-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_material_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='suggested_category',
            field=models.CharField(blank=True, default='', help_text='Categoria sugerida pelo sistema', max_length=50, null=True),
        ),
    ]
