# Generated by Django 5.2 on 2025-08-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_material_suggested_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Identificação do lote (opcional)', max_length=50, verbose_name='Número do Lote'),
        ),
        migrations.AddField(
            model_name='material',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Obrigatório para materiais consumíveis e perecíveis', null=True, verbose_name='Data de Validade'),
        ),
        migrations.AlterField(
            model_name='material',
            name='suggested_category',
            field=models.CharField(blank=True, help_text='Categoria sugerida pelo sistema', max_length=50),
        ),
    ]
