# Generated by Django 5.1.7 on 2025-08-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_material_batch_number_material_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Data de vencimento do material (opcional)', null=True, verbose_name='Data de Validade'),
        ),
    ]
