# Generated by Django 5.2 on 2025-10-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_material_expiration_date'),
        ('laboratories', '0011_laboratory_is_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='invoice',
            field=models.FileField(blank=True, help_text='Arquivo da nota fiscal do material (PDF ou imagem)', null=True, upload_to='invoices/', verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='material',
            name='photo',
            field=models.ImageField(blank=True, help_text='Imagem do material', null=True, upload_to='materials/', verbose_name='Foto do Material'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['name'], name='inventory_m_name_1014de_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['category'], name='inventory_m_categor_73e3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['laboratory'], name='inventory_m_laborat_168aca_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['quantity', 'minimum_stock'], name='inventory_m_quantit_956433_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['laboratory', 'category'], name='inventory_m_laborat_b50a2d_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(condition=models.Q(('expiration_date__isnull', False)), fields=['expiration_date'], name='material_expiration_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['created_at'], name='inventory_m_created_46fd26_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['laboratory', 'quantity'], name='inventory_m_laborat_573bea_idx'),
        ),
    ]
