# Generated by Django 5.2 on 2025-04-07 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('scheduling', 'Agendamentos'), ('inventory', 'Inventário'), ('user_activity', 'Atividade dos Usuários')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_range_start', models.DateField()),
                ('date_range_end', models.DateField()),
                ('filter_params', models.JSONField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
